name: docker-build

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          platforms: linux/amd64
          target: release
          build-args: |
            VERSION=${{ github.ref_name }}
            CSP2_BRANCH=${{ github.ref_name }}
          push: true
          tags: cfsanbiostatistics/csp2:latest,cfsanbiostatistics/csp2:${{ github.ref_name }}
      -
        name: Build for Galaxy
        uses: docker/build-push-action@v6
        with:
          file: docker/Dockerfile
          platforms: linux/amd64
          target: galaxy
          build-args: |
            VERSION=${{ github.ref_name }}
            CSP2_BRANCH=${{ github.ref_name }}
          push: true
          tags: cfsanbiostatistics/csp2:galaxy,cfsanbiostatistics/csp2:${{ github.ref_name }}-galaxy